name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#dev'
        message: Starting build
      if: always()

    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: hello
      run: echo 'hello world'

    - name: C#
      run: |
        dotnet build
        dotnet test

    - name: typescript 
      working-directory: DotnetTemplate.Web
      run: |
        npm install
        npm run build
        npm run lint
        npm t

    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#dev'
        message: Deployed {{ env.GITHUB_REF_NAME }} branch Successfully
      if: always()
